// Barrel for the DB layer. Domains import DB types/managers from `@/db`; the
// concrete Drizzle operators and `*Table` refs stay behind the repository layer.

export type { DBClient, DBManager } from "./db.manager";
export { DrizzleDBManager } from "./db.manager";
export type {
  Activity,
  ActivityCondition,
  ActivityEffort,
  ActivityEquipment,
  ActivityRoute,
  ActivitySummary,
  ActivityTrack,
  EquipmentProfile,
  Favorite,
  JsonArray,
  JsonObject,
  JsonValue,
  NewActivity,
  NewActivityCondition,
  NewActivityEffort,
  NewActivityEquipment,
  NewActivityRoute,
  NewActivitySummary,
  NewActivityTrack,
  NewEquipmentProfile,
  NewFavorite,
  NewRefreshToken,
  NewSpot,
  NewUser,
  NewUserProfile,
  NewUserSportProfile,
  NewWeatherCache,
  NewWeatherMapFrame,
  NewWeatherModelMeta,
  RefreshToken,
  Spot,
  User,
  UserProfile,
  UserSportProfile,
  WeatherCache,
  WeatherMapFrame,
  WeatherModelMeta,
} from "./schema";
