export const AuthReason = {
  // Token problems
  MISSING_TOKEN: "AUTH_MISSING_TOKEN",
  INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  ANONYMOUS_TOKEN_RETIRED: "AUTH_ANONYMOUS_TOKEN_RETIRED",
  USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",

  // Clerk
  CLERK_NOT_CONFIGURED: "AUTH_CLERK_NOT_CONFIGURED",
  CLERK_UNAVAILABLE: "AUTH_CLERK_UNAVAILABLE",

  // Link / merge
  NOT_ANONYMOUS: "AUTH_NOT_ANONYMOUS",
  ALREADY_LINKED: "AUTH_ALREADY_LINKED",
} as const;
