export const SpotReason = {
  NOT_FOUND: "SPOT_NOT_FOUND",
  ALREADY_FAVORITED: "SPOT_ALREADY_FAVORITED",
  FAVORITE_NOT_FOUND: "SPOT_FAVORITE_NOT_FOUND",
  PRIVATE_SPOT_LIMIT: "SPOT_PRIVATE_LIMIT_REACHED",
} as const;
